# Generated by Django 5.0 on 2023-12-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_alter_userfollows_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
