# Generated by Django 5.0 on 2023-12-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_userfollows_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
