# Generated by Django 5.0 on 2023-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0005_remove_userfollows_is_blocked_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
