# Generated by Django 5.0 on 2023-12-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0006_userfollows_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollows',
            name='is_blocked',
        ),
    ]
