# Generated by Django 5.0 on 2023-12-27 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_alter_userfollows_user'),
        ('authentication', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='app_web.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
