# Generated by Django 5.0 on 2024-01-11 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0008_alter_review_body'),
        ('authentication', '0005_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(through='app_web.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
